### PR TITLE
0.3.0

### LINKED ISSUE #13: createNewUser callback is never called
callback is never called, any idea on what could be causing this? Am I missing a setting?

       var newUser = new User({
          name: req.body.name,
          password: md5(req.body.password),
          email: req.body.email
        });

        nev.createTempUser(newUser, function(err, newTempUser) {
          if(newTempUser) {
            nev.registerTempUser(newTempUser, function(err) {
              res.json({sucess: true, message: 'An email has been sent for verification'});
            });
          } else {
            res.json({success: false, message: 'This username is awaiting verification, please check your email'});
          }
        });

### PR DESCRIPTION
**Pull request by SaintDako**
a few changes:

- closes #13 by passing `mongoose` to the `require` statement of NEV
- all JS files are indented with 2 spaces instead of 4 (except for tests... whoops)
- README is now fixed to show the old API changes and the change above
- switched from bcrypt to bcryptjs because I was having really, really annoying problems installing bcrypt with the newest version of Node
- added .travis.yml file to setup Travis CI testing, closing #11

### CODE REVIEW

**Comment by SaintDako** [comment]
@MichaelTaylor3D if you could grab this branch and tell me what you think, that'd be awesome

@frankcash if you can skim this, that too would be awesome

**Comment by frankcash** [comment]
I'll be able to look at it this afternoon.

**Comment by SaintDako** [comment]
yay, Travis CI is working!

**Comment by frankcash** [comment]
Woo!

**Comment by frankcash** [comment]
```
node_js:
  - "0.10"
```

:worried:

**Comment by SaintDako** [comment]
Travis CI said that's the stable version of Node, although later versions are supported too. perhaps I should add 0.12 and 4.0.0

**Comment by frankcash** [comment]
I think supporting 4.0.0+ is the way to go since 0.10.0 and 0.12.0 are dead branches, they are LTS though but I think the 4.0.0 path broke compatibility for some libs.

**Comment by SaintDako** [comment]
alright updated travis for 4.1.0, because YOLO

but for real, 4.2.x works on my machine with NEV so whatever. merging

**Pull request merged**
