### PR TITLE
Added tests and added synchronous calls

### PR DESCRIPTION
**Pull request by whitef0x0**
Added more testing and made calls synchronous / added callbacks to asynchronous functions.

### CODE REVIEW

**Comment by SaintDako** [comment]
if you can remind me on this weekend / Monday to take a look at this, I will. currently a bit busy as I mentioned before, but I appreciate the contribution!

**Comment by whitef0x0** [comment]
Hey.

Have you had a chance to look at this yet?

**Comment by SaintDako** [comment]
hey! I didn't even see this! I didn't get an email notification or anything like that. I will try to look at it tomorrow. apologies!

**Comment by SaintDako** [comment]
I'm going to leave some comments tonight, and I'll leave some more tomorrow. I'll post another comment when I'm done reviewing

**Comment by SaintDako** [comment]
scratch that - I'm going to accept the PR and fix some style issues later.

**Pull request merged**
