### PR TITLE
0.4.1

### PR DESCRIPTION
**Pull request by SaintDako**
this actually contains a big bug fix - I removed `JSON.parse(JSON.stringifiy(options.mailOptions)` before which actually made a deep copy of the `mailOptions` object. that's what we want, since we change the `text` field to contain the URL verification route (with `${URL}` in it) and then replace that with the URL for the user. however, by removing the deep copy, what happened was, e.g.

- user signs up, is assigned URL `somerandomurl`
- `mailOptions.text = 'visit localhost:8000/${URL}'` --> `mailOptions.text = ''visit localhost:8000/somerandomurl'`
- different user signs up, is assigned URL `NOTTHESAMEURL`
- `mailOptions.text` tries to replace `${URL}` with `'NOTTHESAMEURL'` but we actually didn't deep copy `mailOptions` so it's what it was before!
- email with old URL is sent

will add more commits with the throwing errors for options (for #21).

### CODE REVIEW

**Comment by frankcash** [comment]
Will check it out tonight.

**Comment by SaintDako** [comment]
didn't put it in commit message but this closes #21

**Comment by frankcash** [comment]
I ran the example code and never received an email

**Comment by frankcash** [comment]
promised example fails, lack of `blue-bird` but if you add it to either the deps/ dev-deps it runs.

**Comment by SaintDako** [comment]
did you change the params passed? it worked for me... lemme double check tho

**Comment by frankcash** [comment]
Params passed? as in the user? yes, I will create a new gmail account and pass in those params. could be something with my auth.

**Comment by frankcash** [comment]
Guess we should make people aware of this

google-email-defense

**Comment by SaintDako** [comment]
ah yeah, I forgot that was a thing until I ran into it recently again. the email I use is set to be less secure.

what I might do is set up a separate email account for this package specifically with those less secure settings, keep the email & password in the params, and then enable two-factor auth so that no one can actually login... do you think that would work?

**Comment by frankcash** [comment]
ya

**Comment by SaintDako** [comment]
yeah, it didn't work :cry:

**Comment by frankcash** [comment]
Rip, I'll mess with gmail settings in the morning.

**Comment by SaintDako** [comment]
I'll PM you the email info I was using before

**Comment by frankcash** [comment]
Sounds good

**Comment by frankcash** [comment]
Both servers worked on node `4.1.1`

**Comment by SaintDako** [comment]
neat.jpg

**Pull request merged**
